import { QuizQuestion } from './courseData';

// 每个付费章节的12题综合测试
export const CHAPTER_QUIZZES: Record<string, QuizQuestion[]> = {
  // ==========================================
  // ch1: 技术分析基础
  // ==========================================
  ch1: [
    { question: '阳线（绿色K线）表示什么？', options: ['收盘价高于开盘价', '收盘价低于开盘价', '价格没有变化', '成交量增加'], correctIndex: 0, explanation: '阳线意味着这段时间内价格上涨了——收盘价高于开盘价。' , questionEn: 'What does a bullish (green) candle indicate?', optionsEn: ['Close above open', 'Close below open', 'No price change', 'Volume increase'], explanationEn: 'A bullish candle means price rose — close is higher than open.' },
    { question: '长下影线的K线出现在下跌趋势底部，通常叫什么？', options: ['射击之星', '十字星', '锤子线', '吞没形态'], correctIndex: 2, explanation: '锤子线（Hammer）特征是小实体+长下影线，出现在下跌底部是潜在反转信号。' , questionEn: 'A candle with a long lower wick at a downtrend bottom is called?', optionsEn: ['Shooting star', 'Doji', 'Hammer', 'Engulfing'], explanationEn: 'A Hammer: small body + long lower wick. At a downtrend bottom, potential reversal signal.' },
    { question: '支撑位被跌破后，它通常会变成什么？', options: ['更强的支撑', '阻力位', '无效水平', '买入信号'], correctIndex: 1, explanation: '角色互换原则：被突破的支撑变阻力，被突破的阻力变支撑。' , questionEn: 'After support is broken, it usually becomes?', optionsEn: ['Stronger support', 'Resistance', 'Invalid level', 'Buy signal'], explanationEn: 'Role reversal: broken support becomes resistance, broken resistance becomes support.' },
    { question: '哪种方式画支撑阻力最正确？', options: ['精确到小数点的线', '一个价格区域（区间）', '只看最近一天的', '用移动平均线替代'], correctIndex: 1, explanation: '支撑阻力是一个"区域"而不是精确的线。用区域画能避免被假突破误导。' , questionEn: 'Correct way to draw support/resistance?', optionsEn: ['Precise line to decimals', 'A price zone (range)', 'Only last day\'s', 'Use MAs instead'], explanationEn: 'S/R are zones, not exact lines. Zones avoid false breakout traps.' },
    { question: '上升趋势的严格定义是什么？', options: ['价格在涨', '不断创新高且回调不破前低', 'MA金叉', '成交量放大'], correctIndex: 1, explanation: '上升趋势 = Higher Highs + Higher Lows（更高的高点+更高的低点）。' , questionEn: 'Strict definition of an uptrend?', optionsEn: ['Price is rising', 'Continuously higher highs and higher lows', 'MA golden cross', 'Volume increasing'], explanationEn: 'Uptrend = Higher Highs + Higher Lows.' },
    { question: 'EMA9上穿EMA21叫什么？', options: ['死叉', '金叉', '十字星', '吞没'], correctIndex: 1, explanation: '短期均线上穿长期均线称为金叉（Golden Cross），是看涨信号。' , questionEn: 'EMA9 crossing above EMA21 is called?', optionsEn: ['Death cross', 'Golden cross', 'Doji', 'Engulfing'], explanationEn: 'Short-term MA crossing above long-term MA = Golden Cross, a bullish signal.' },
    { question: '价格突破阻力位但成交量没有放大，最可能是什么？', options: ['强势突破', '假突破', '趋势加速', '底部反转'], correctIndex: 1, explanation: '有效突破需要放量确认。无量突破大概率是假突破。' , questionEn: 'Price breaks resistance without volume increase — most likely?', optionsEn: ['Strong breakout', 'False breakout', 'Trend acceleration', 'Bottom reversal'], explanationEn: 'Valid breakouts need volume confirmation. No volume = likely false.' },
    { question: '在上升趋势中，健康的量价关系是什么？', options: ['上涨缩量，回调放量', '上涨放量，回调缩量', '始终放量', '始终缩量'], correctIndex: 1, explanation: '健康上升趋势：上涨时放量（买方积极）、回调时缩量（卖压轻微）。' , questionEn: 'Healthy volume-price relationship in an uptrend?', optionsEn: ['Rise low vol, pullback high vol', 'Rise high vol, pullback low vol', 'Always high vol', 'Always low vol'], explanationEn: 'Healthy: volume up on rallies, down on pullbacks.' },
    { question: '暴跌+极端放量通常意味着什么？', options: ['还会继续跌', '恐慌性抛售，可能接近底部', '趋势开始', '正常波动'], correctIndex: 1, explanation: '极端放量暴跌 = 投降式抛售。想卖的人都卖完了，反而可能是底部信号。' , questionEn: 'Crash + extreme volume typically means?', optionsEn: ['More downside', 'Panic selling, possibly near bottom', 'Trend starting', 'Normal fluctuation'], explanationEn: 'Extreme volume crash = capitulation. All sellers exhausted — potential bottom signal.' },
    { question: '单根K线形态构成完整交易信号吗？', options: ['是的，足够了', '不够，还要结合位置、趋势和成交量', '只在日线有效', '只对BTC有效'], correctIndex: 1, explanation: 'K线形态需要在正确的位置（支撑/阻力）+ 正确的趋势方向 + 成交量确认才有意义。' , questionEn: 'Does a single candle pattern constitute a complete signal?', optionsEn: ['Yes', 'No — combine with location, trend, volume', 'Only on daily', 'Only for BTC'], explanationEn: 'Candle patterns need right location + trend direction + volume confirmation.' },
    { question: '在下降趋势中，MA通常充当什么角色？', options: ['支撑', '动态阻力', '无效', '买入信号'], correctIndex: 1, explanation: '下降趋势中，每次价格反弹到MA附近都容易受阻回落，MA充当动态阻力。' , questionEn: 'In a downtrend, MA usually acts as?', optionsEn: ['Support', 'Dynamic resistance', 'Irrelevant', 'Buy signal'], explanationEn: 'In downtrends, price stalls at MA — acts as dynamic resistance.' },
    { question: '以下哪个不属于K线的4个价格？', options: ['开盘价', '收盘价', '平均价', '最高价'], correctIndex: 2, explanation: 'K线包含4个价格：开盘价(O)、收盘价(C)、最高价(H)、最低价(L)。平均价不是K线的组成部分。' , questionEn: 'Which is NOT one of a candle\'s 4 prices?', optionsEn: ['Open', 'Close', 'Average price', 'High'], explanationEn: 'Candles: Open, Close, High, Low. Average price is not a candlestick component.' },
  ],

  // ==========================================
  // ch2: 偏向判定系统
  // ==========================================
  ch2: [
    { question: '偏向（Bias）的三种类型是什么？', options: ['买入、卖出、持有', '看涨、看跌、横盘', '短线、中线、长线', '现货、期货、期权'], correctIndex: 1, explanation: '偏向分为看涨、看跌和横盘三种。很多人忽略横盘偏向，导致在震荡市中反复被止损。' , questionEn: 'What are the three types of bias?', optionsEn: ['Buy, sell, hold', 'Bullish, bearish, sideways', 'Short/mid/long-term', 'Spot, futures, options'], explanationEn: 'Bias: bullish, bearish, sideways. Many ignore sideways, leading to repeated stop-outs.' },
    { question: '"偏向第一，入场第二"意味着什么？', options: ['先买再想', '先判断方向再找入场点', '偏向不重要', '只看入场不看方向'], correctIndex: 1, explanation: '方向比时机更重要。偏向对了，入场差一点也能赚；偏向错了，入场再完美也亏。' , questionEn: 'What does \'bias first, entry second\' mean?', optionsEn: ['Buy first, think later', 'Determine direction before entry', 'Bias doesn\'t matter', 'Only look at entry'], explanationEn: 'Direction > timing. Right bias + poor entry profits; wrong bias + perfect entry loses.' },
    { question: '做2天波段交易，应该看什么时间框架判断偏向？', options: ['1小时', '4小时', '日线', '月线'], correctIndex: 3, explanation: '×12乘数法则：2天×12≈月线。做波段需要看月线级别确定大方向。' , questionEn: 'For 2-day swings, what timeframe for bias?', optionsEn: ['1-hour', '4-hour', 'Daily', 'Monthly'], explanationEn: '×12 rule: 2 days × 12 ≈ monthly for direction.' },
    { question: '月线转空但周线还在涨，应该怎么做？', options: ['立刻做空', '跟周线偏向做多，等周线也转空再做空', '不交易', '加杠杆做空'], correctIndex: 1, explanation: '偏向溢出需要时间。月线转空不代表周线立刻转空，可能还有最后一波上涨。' , questionEn: 'Monthly bearish but weekly bullish — what to do?', optionsEn: ['Short immediately', 'Follow weekly long, short after weekly turns too', 'Don\'t trade', 'Short with leverage'], explanationEn: 'Spillover takes time. May have one last rally.' },
    { question: '用RSI+MACD+MA同时看涨等于3倍确信度吗？', options: ['是的', '不是，它们高度相关', '取决于时间框架', 'RSI最准'], correctIndex: 1, explanation: '这三个指标都从价格衍生，高度相关。需要用不同维度（成交量、波动率、持仓等）才能获得真正的独立确认。' , questionEn: 'RSI + MACD + MA all bullish = 3x confidence?', optionsEn: ['Yes', 'No, highly correlated', 'Depends on TF', 'RSI most accurate'], explanationEn: 'All price-derived, correlated. Need different dimensions for independent confirmation.' },
    { question: '低相关性信号系统的6个维度不包括哪个？', options: ['价格', '时间', 'Twitter粉丝数', '波动率'], correctIndex: 2, explanation: '6个维度是：价格、时间、成交量、波动率、订单流、持仓定位。社交媒体粉丝数不是独立维度。' , questionEn: 'Which is NOT one of the 6 low-correlation dimensions?', optionsEn: ['Price', 'Time', 'Twitter followers', 'Volatility'], explanationEn: '6 dimensions: price, time, volume, volatility, order flow, positioning.' },
    { question: '偏向持续规则中，偏向持续到什么时候？', options: ['价格目标被触及', 'K线收盘', '你觉得够了', '止盈时'], correctIndex: 1, explanation: '偏向持续到K线收盘，不是到价格目标。时间>价格。' , questionEn: 'Bias persists until?', optionsEn: ['Price target hit', 'Candle close', 'You feel enough', 'Take-profit'], explanationEn: 'Bias persists to candle close, not price target. Time > Price.' },
    { question: '综合信号评分0.7意味着什么？', options: ['完全不可信', '很弱', '可以建仓', '极强信号，可重仓'], correctIndex: 3, explanation: '0.7-1.0区间是强信号区，多个独立维度同时确认，可以考虑较重仓位。' , questionEn: 'Composite signal score of 0.7 means?', optionsEn: ['Unreliable', 'Very weak', 'Can open positions', 'Strong signal, can size up'], explanationEn: '0.7-1.0 = strong signal zone, multiple dimensions confirming.' },
    { question: '如果你不确定市场方向，最好的做法是？', options: ['做多', '做空', '不交易', '同时做多做空'], correctIndex: 2, explanation: '不确定方向=横盘偏向。"不交易"就是最好的交易。等方向明确再出手。' , questionEn: 'Unsure about direction — best action?', optionsEn: ['Go long', 'Go short', 'Don\'t trade', 'Long and short'], explanationEn: 'Unsure = sideways. Not trading is the best trade.' },
    { question: 'Type 1 K线和Type 2/3 K线的区别是？', options: ['颜色不同', 'Type 1方向明确可交易，Type 2/3震荡不适合交易', '时间框架不同', '没有区别'], correctIndex: 1, explanation: 'Type 1是趋势型K线（方向明确），Type 2/3是震荡型（方向模糊）。只交易Type 1。' , questionEn: 'Difference between Type 1 and Type 2/3 candles?', optionsEn: ['Colors', 'Type 1 clear direction, tradeable; Type 2/3 choppy', 'Timeframes', 'No difference'], explanationEn: 'Type 1 = trending, Type 2/3 = ranging. Only trade Type 1.' },
    { question: '关于偏向溢出，以下哪个说法正确？', options: ['高时间框架转空后低时间框架立刻跟随', '最后一波通常很强', '偏向不会从高级别传到低级别', '只有日线偏向重要'], correctIndex: 1, explanation: '偏向转换完成前的"最后一波"通常特别强烈。在月线转空前的最后一波上涨可能很猛。' , questionEn: 'About bias spillover, which is correct?', optionsEn: ['Higher TF bearish immediately affects lower', 'Last wave is usually strongest', 'Bias doesn\'t flow between TFs', 'Only daily matters'], explanationEn: 'The last wave before transition is often the strongest.' },
    { question: '"我只看下一个移动"这个原则的意义是？', options: ['不要做长线', '专注当下，不预测太远', '只做1分钟交易', '不看图表'], correctIndex: 1, explanation: '在每个时间框架上专注"下一步"，不要试图预测3步之后。这样在每个时间框架上都能成功。' , questionEn: 'Significance of \'I only look at the next move\'?', optionsEn: ['Don\'t do long-term', 'Focus on present, don\'t predict far', 'Only 1-min trades', 'Don\'t look at charts'], explanationEn: 'Focus on the next step, don\'t predict 3 moves ahead.' },
  ],

  // ==========================================
  // ch3: 顶底信号系统
  // ==========================================
  ch3: [
    { question: '顶部分数0.5-0.7意味着什么？', options: ['远离顶部', '接近风险区，开始制定卖出计划', '确认顶部', '应该全仓买入'], correctIndex: 1, explanation: '0.5-0.7区间意味着接近但不急。正确做法是开始准备卖出计划，而不是立刻行动。' , questionEn: 'Top score 0.5-0.7 means?', optionsEn: ['Far from top', 'Approaching — prepare sell plan', 'Top confirmed', 'Go all in'], explanationEn: 'Approaching but not urgent. Prepare sell plan.' },
    { question: '为什么卖出是"阶梯式"的？', options: ['因为手续费', 'BTC长期向上+税务+卖太早代价大', '只是习惯', '没有原因'], correctIndex: 1, explanation: 'BTC长期趋势上涨、卖出有税、卖太早比卖太晚代价大，所以用渐进式卖出更合理。' , questionEn: 'Why is selling done in \'steps\'?', optionsEn: ['Fees', 'BTC uptrend + taxes + selling early costs more', 'Habit', 'No reason'], explanationEn: 'BTC trends up, tax on sales, early selling > late selling — gradual is rational.' },
    { question: '底部分数<0.4时应该怎么做？', options: ['全仓买入', '等待，不着急', '做空', '清仓'], correctIndex: 1, explanation: '分数不到0.4说明底部还没确认。正确做法是准备资金、保持耐心。' , questionEn: 'What to do when bottom score < 0.4?', optionsEn: ['All in', 'Wait, no rush', 'Short', 'Clear positions'], explanationEn: 'Below 0.4 = not confirmed. Prepare capital and wait.' },
    { question: '"精准出手"vs"DCA定投"，本课推荐哪个？', options: ['DCA', '精准出手', '两者结合', '都不推荐'], correctIndex: 1, explanation: '等底部分数足够高再集中建仓，比无脑定投在心理和实际回报上都更优。' , questionEn: '\'Precision strikes\' vs DCA — recommended?', optionsEn: ['DCA', 'Precision strikes', 'Both', 'Neither'], explanationEn: 'Wait for score then concentrate. Better than DCA in psychology and returns.' },
    { question: '顶部分数的峰值和底部分数有什么关系？', options: ['没有关系', '顶部分数峰值决定底部分数的底线', '完全相反', '一样的'], correctIndex: 1, explanation: '顶部分数不高=顶部不极端=底部也不会太深。这是镜像关系。' , questionEn: 'Relationship between top score peaks and bottom scores?', optionsEn: ['None', 'Top peak determines bottom floor', 'Opposite', 'Same'], explanationEn: 'Lower top peak = less extreme top = shallower bottom. Mirror relationship.' },
    { question: '波段交易6步系统的第一步是什么？', options: ['找入场点', '设止损', '判断周期位置', '选择交易对'], correctIndex: 2, explanation: '第一步永远是用顶底分数判断周期位置，这决定做多还是做空。' , questionEn: 'First step of Swing Trading 6-Step System?', optionsEn: ['Find entry', 'Set stop loss', 'Determine cycle position', 'Choose pair'], explanationEn: 'Step one: top/bottom scores for cycle position → long or short.' },
    { question: '底部分数用什么来"确认"买入时机？', options: ['分数达到目标值+开始上升', '分数达到0就买', '别人说买就买', '价格创新低就买'], correctIndex: 0, explanation: '需要分数达到阈值且开始改善才入场。光到低位不够，要看到回升趋势。' , questionEn: 'How does bottom score \'confirm\' buy timing?', optionsEn: ['Reaches target AND starts rising', 'Buy at score 0', 'Others say buy', 'Buy at new lows'], explanationEn: 'Score must reach threshold AND improve. Low alone isn\'t enough.' },
    { question: '关于All-in/All-out策略的"时间衰减规则"，它的作用是？', options: ['加速亏损', '确保最终一定会买入/卖出', '减少手续费', '提高杠杆'], correctIndex: 1, explanation: '时间衰减规则每月+1到有效计数，确保即使分数未达极端，经过足够时间后也会执行。避免永远被冻结。' , questionEn: 'Purpose of \'time decay rule\' in All-in/All-out?', optionsEn: ['Accelerate losses', 'Ensure eventual execution', 'Reduce fees', 'Increase leverage'], explanationEn: '+1 monthly ensures action even without extreme scores. Prevents permanent freeze.' },
    { question: '在已确认偏向方向上，大约多少比例的月K线会顺着偏向走？', options: ['50%', '60%', '70%', '90%'], correctIndex: 2, explanation: '统计显示约70%的月K线会顺偏向方向，且顺势K线比逆势K线更大。' , questionEn: 'In confirmed bias, what % of monthly candles follow?', optionsEn: ['50%', '60%', '70%', '90%'], explanationEn: '~70% follow bias, and trend candles are larger than counter-trend.' },
    { question: '6步系统中的"部分止盈"是在什么条件下执行？', options: ['赚$100就止盈', 'K线耗尽/接近支撑阻力/利润≥2R', '每天下午3点', '感觉差不多了'], correctIndex: 1, explanation: '部分止盈的触发条件是客观的：动量减弱、接近关键水平、或利润达到2R以上。' , questionEn: 'When is \'partial take-profit\' executed?', optionsEn: ['At $100 profit', 'Exhaustion / near S&R / profit ≥ 2R', 'Daily at 3 PM', 'Feels right'], explanationEn: 'Objective: weakening momentum, near key levels, or profit ≥ 2R.' },
    { question: '"Range→Trend→Range→Trend"模型告诉我们什么？', options: ['市场只涨不跌', '市场永远在横盘和趋势之间交替', '只做横盘', '只做趋势'], correctIndex: 1, explanation: '市场只做两件事：横盘和趋势。理解这个模型后，在不同阶段用不同策略。' , questionEn: 'What does \'Range→Trend→Range→Trend\' tell us?', optionsEn: ['Only goes up', 'Alternates between ranging and trending', 'Only range', 'Only trend'], explanationEn: 'Market does two things: range and trend. Different strategies for each.' },
    { question: '35%的"偏向无效化止损"听起来很宽，为什么这样设计？', options: ['鼓励不止损', '这是偏向级别的止损，通过小仓位控制实际风险', '只是建议', '不重要'], correctIndex: 1, explanation: '35%是偏向无效化的止损距离，配合小仓位（0.5x杠杆）实际风险被控制在合理范围内。' , questionEn: '35% \'bias invalidation stop\' sounds wide — why?', optionsEn: ['No stops', 'Bias-level stop; risk via small positions', 'Suggestion', 'Not important'], explanationEn: '35% = bias invalidation distance; actual risk controlled via 0.5x leverage.' },
  ],

  // ==========================================
  // ch4: 情绪与市场心理
  // ==========================================
  ch4: [
    { question: '情绪和价格的关系是什么？', options: ['完全同步', '情绪和价格不同步，情绪受时间影响更大', '没有关系', '价格决定一切'], correctIndex: 1, explanation: '时间对情绪的影响>价格对情绪的影响。价格暴跌后恐惧会持续很久（不信反弹），见顶后乐观还会维持（自满下跌）。' , questionEn: 'Relationship between sentiment and price?', optionsEn: ['Perfectly synced', 'Not synced — sentiment more influenced by time', 'None', 'Price = everything'], explanationEn: 'Time > price for sentiment. Fear lingers after crashes; optimism persists after tops.' },
    { question: '情绪指标降到0.10但还在下降，应该买入吗？', options: ['是的', '不急，等开始上升才买', '做空', '无视'], correctIndex: 1, explanation: '买入条件是"<0.15+开始转绿"。光到低位不够，情绪可以在极端位置停留很长时间。' , questionEn: 'Sentiment at 0.10, still falling — buy?', optionsEn: ['Yes', 'Wait for rising', 'Short', 'Ignore'], explanationEn: 'Buy = <0.15 AND turning green. Extremes can persist.' },
    { question: 'Fear & Greed Index中，25%的权重来自什么？', options: ['社交媒体', '波动率', 'Google趋势', 'BTC主导率'], correctIndex: 1, explanation: 'F&G Index中波动率和市场动量各占25%，是最大的两个权重因素。' , questionEn: 'What is 25% of F&G Index weight?', optionsEn: ['Social media', 'Volatility', 'Google Trends', 'BTC dominance'], explanationEn: 'Volatility and momentum each = 25%.' },
    { question: '2026年2月的Fear & Greed值是5，这在历史上属于什么水平？', options: ['正常', '稍微恐惧', '历史极端恐惧', '贪婪'], correctIndex: 2, explanation: 'F&G值5是历史极端恐惧水平。历史上F&G<10时，1年后回报平均+200%。' , questionEn: 'Feb 2026 F&G = 5 — historical level?', optionsEn: ['Normal', 'Slightly fearful', 'Extreme fear', 'Greedy'], explanationEn: 'F&G 5 = extreme fear. F&G < 10 historically → avg +200% 1-year return.' },
    { question: '情绪指标在交易系统中的角色是什么？', options: ['独立交易信号', '最后的确认工具', '唯一指标', '不重要'], correctIndex: 1, explanation: '情绪不是独立信号，是最后的确认。先用偏向判断方向，再用顶底分数判断位置，最后用情绪确认。' , questionEn: 'Sentiment indicator\'s role?', optionsEn: ['Independent signal', 'Final confirmation', 'Only needed', 'Not important'], explanationEn: 'Final confirmation. Bias → scores → sentiment.' },
    { question: '"当你恐惧到不敢买时"，应该问自己什么？', options: ['别人怎么看', '恐惧是因为基本面恶化还是因为价格下跌', '要不要加杠杆', '该不该换币'], correctIndex: 1, explanation: '区分恐惧来源：基本面恶化=合理恐惧；仅因价格下跌=情绪恐惧（反而是买入信号）。' , questionEn: '\'Too scared to buy\' — ask yourself?', optionsEn: ['Others\' view', 'Fear from fundamentals or just price?', 'Add leverage?', 'Switch coins?'], explanationEn: 'Fundamentals deteriorating = rational fear; price-decline fear = buy signal.' },
    { question: '情绪日志应该记录什么？', options: ['只记价格', '第一反应、F&G值、新闻标题', '只记盈亏', '什么都不记'], correctIndex: 1, explanation: '每天记录：打开行情的第一反应、F&G值、新闻标题偏向。坚持后能发现自己的情绪模式。' , questionEn: 'Sentiment journal records?', optionsEn: ['Only price', 'First reaction, F&G, headlines', 'Only P&L', 'Nothing'], explanationEn: 'Daily: first reaction, F&G value, news sentiment.' },
    { question: '为什么说"你的情绪经常和市场同步"？', options: ['这是好事', '说明你就是散户指标，需要反向操作', '不可能', '只在牛市'], correctIndex: 1, explanation: '如果你的情绪和大多数散户同步，那你的恐惧/贪婪就是反向信号。识别后可以用反向思维对抗。' , questionEn: 'Why \'emotions sync with market\'?', optionsEn: ['Good', 'You\'re the retail indicator — go contrarian', 'Impossible', 'Bull only'], explanationEn: 'If your emotions match retail, your fear/greed is a contrarian signal.' },
    { question: '0-1情绪量表中，0.3-0.7区间属于什么状态？', options: ['极端恐惧', '中性', '极端贪婪', '买入区'], correctIndex: 1, explanation: '0.3-0.7是中性区间，正常操作即可。只有极端值（<0.15或>0.85）才是重要信号。' , questionEn: '0-1 sentiment scale: 0.3-0.7 range?', optionsEn: ['Extreme fear', 'Neutral', 'Extreme greed', 'Buy zone'], explanationEn: '0.3-0.7 = neutral. Only extremes matter.' },
    { question: '情绪指标在什么位置"开始转绿"是买入条件？', options: ['0.85以上', '0.50', '0.15以下', '任何位置'], correctIndex: 2, explanation: '情绪<0.15且开始上升（转绿）是买入条件。必须在极端恐惧区域且开始改善。' , questionEn: 'At what level does \'turning green\' = buy condition?', optionsEn: ['Above 0.85', '0.50', 'Below 0.15', 'Any'], explanationEn: '<0.15 AND rising = buy. Must be extreme fear AND improving.' },
    { question: '以下哪个不是F&G Index的组成因素？', options: ['波动率', '社交媒体', 'AI预测', 'Google趋势'], correctIndex: 2, explanation: 'F&G由波动率、市场动量、社交媒体、调查、BTC主导率和Google趋势组成，没有AI预测。' , questionEn: 'Which is NOT an F&G component?', optionsEn: ['Volatility', 'Social media', 'AI predictions', 'Google Trends'], explanationEn: 'No AI predictions. F&G = volatility, momentum, social, surveys, BTC dom, Google.' },
    { question: '情绪指标最大的价值是什么？', options: ['告诉你具体买卖点', '提供客观的市场情绪度量，帮你对抗自身情绪', '替代技术分析', '预测未来价格'], correctIndex: 1, explanation: '情绪指标的核心价值是给你一个客观数字，帮你在极端情绪中保持理性，避免被恐惧/贪婪驱动。' , questionEn: 'Greatest value of sentiment indicators?', optionsEn: ['Exact points', 'Objective measure to counter emotions', 'Replace TA', 'Predict prices'], explanationEn: 'Objective number for rational decision-making during extremes.' },
  ],

  // ==========================================
  // ch5: 交易心理学
  // ==========================================
  ch5: [
    { question: '人类对亏损的痛苦感是对获利快感的几倍？', options: ['1倍', '1.5倍', '2-2.5倍', '5倍'], correctIndex: 2, explanation: '行为经济学研究表明损失厌恶系数约2-2.5。这是不愿止损的生物学根源。' , questionEn: 'Pain of loss vs pleasure of gain?', optionsEn: ['1x', '1.5x', '2-2.5x', '5x'], explanationEn: 'Loss aversion ~2-2.5x. Biological root of stop-loss reluctance.' },
    { question: 'FOMO来了，最好的第一步是什么？', options: ['立刻买入', '强制等待至少15分钟', '加杠杆', '问群友'], correctIndex: 1, explanation: '延迟决策让前额叶重新接管。大多数FOMO冲动在等待中会消退。' , questionEn: 'When FOMO hits, best first step?', optionsEn: ['Buy now', 'Force 15-min wait', 'Add leverage', 'Ask groups'], explanationEn: 'Delay lets rational brain regain control. Most FOMO fades.' },
    { question: '"我已经亏了$200，再亏一点也无所谓"是什么心理陷阱？', options: ['FOMO', '沉没成本谬误', '确认偏误', '锚定效应'], correctIndex: 1, explanation: '沉没成本谬误让你因为已投入的成本而非理性决策。应该只问"从现在开始值不值得"。' , questionEn: '\'Lost $200, more doesn\'t matter\' — what trap?', optionsEn: ['FOMO', 'Sunk cost fallacy', 'Confirmation bias', 'Anchoring'], explanationEn: 'Sunk cost: decisions based on past costs. Only ask \'worth holding now?\'' },
    { question: '连亏2笔后最安全的做法是？', options: ['加大仓位', '当天停止交易', '换策略', '借钱继续'], correctIndex: 1, explanation: '连亏后情绪状态不适合继续。休息一晚让大脑恢复理性。' , questionEn: 'Safest action after 2 losses?', optionsEn: ['Increase position', 'Stop for the day', 'Switch strategy', 'Borrow more'], explanationEn: 'Post-loss state unsuitable for trading. Rest overnight.' },
    { question: '连亏后恢复交易，仓位应该怎样？', options: ['加大', '不变', '缩小到平时1/3', '全仓'], correctIndex: 2, explanation: '缩小仓位是为了重建节奏和信心，连续盈利5笔后再恢复正常。' , questionEn: 'Resuming after losses — position size?', optionsEn: ['Larger', 'Same', '1/3 of normal', 'All-in'], explanationEn: '1/3 rebuilds rhythm/confidence. Normal after 5 consecutive wins.' },
    { question: '过度交易的隐形杀手是什么？', options: ['行情波动', '手续费', '时间', '心态'], correctIndex: 1, explanation: '$500账户10x杠杆每天10笔交易，一个月手续费可能超过$1000——比本金还多。' , questionEn: 'Hidden killer of overtrading?', optionsEn: ['Volatility', 'Fees', 'Time', 'Mindset'], explanationEn: '$500 account, 10x leverage, 10 trades/day → $1000+/month fees.' },
    { question: '交易仪式的核心目的是什么？', options: ['浪费时间', '把纪律变成习惯，不消耗意志力', '好看', '给别人看的'], correctIndex: 1, explanation: '意志力是有限资源。仪式/习惯不消耗意志力，一旦养成就自动执行。' , questionEn: 'Core purpose of trading ritual?', optionsEn: ['Waste time', 'Discipline → habit, no willpower', 'Look pro', 'For show'], explanationEn: 'Willpower is limited. Habits = automatic execution.' },
    { question: '交易前情绪状态只有4/10分，应该怎么做？', options: ['照常交易', '不交易或大幅缩小仓位', '用交易改善心情', '加仓'], correctIndex: 1, explanation: '情绪差时决策质量下降。<6分建议不交易或缩小仓位。用交易"改善心情"是过度交易的根源。' , questionEn: 'Pre-trade emotions 4/10 — what to do?', optionsEn: ['Normal trading', 'Don\'t trade / cut position', 'Trade to improve mood', 'Increase position'], explanationEn: 'Poor emotions = poor decisions. <6: skip or cut.' },
    { question: '以下哪个不是恐惧在交易中的表现？', options: ['不愿止损', '害怕入场', '耐心等待好机会', '报复性交易'], correctIndex: 2, explanation: '耐心等待是纪律的表现，不是恐惧。不愿止损、害怕入场、报复性交易都是恐惧的不同表现。' , questionEn: 'Which is NOT trading fear?', optionsEn: ['Refusing stop loss', 'Afraid to enter', 'Patiently waiting', 'Revenge trading'], explanationEn: 'Patient waiting = discipline, not fear.' },
    { question: '"确认偏误"在交易中的表现是什么？', options: ['确认订单', '只关注支持自己观点的信息', '确认止损', '确认趋势'], correctIndex: 1, explanation: '确认偏误让你只看"BTC即将反弹"的文章，忽略所有看跌证据，导致不止损。' , questionEn: '\'Confirmation bias\' in trading?', optionsEn: ['Confirming orders', 'Only seeking supporting info', 'Confirming stop', 'Confirming trend'], explanationEn: 'Only reading \'BTC will bounce\' while ignoring bearish evidence.' },
    { question: '专业交易者的正常胜率大约是？', options: ['80-90%', '60-80%', '40-60%', '<30%'], correctIndex: 2, explanation: '成功交易者胜率通常40-60%。关键不是高胜率，而是"赢多输少"的R:R。' , questionEn: 'Professional trader win rate?', optionsEn: ['80-90%', '60-80%', '40-60%', '<30%'], explanationEn: '40-60%. Key: win big, lose small (good R:R).' },
    { question: '"每日最多3笔"规则的意义是什么？', options: ['赚不了钱', '控制过度交易，确保每笔都是高质量', '限制收益', '没必要'], correctIndex: 1, explanation: '硬性限制迫使你只做最好的机会。质量远比数量重要。每月10笔高质量交易>每天10笔低质量交易。' , questionEn: '\'Max 3 trades/day\' rule significance?', optionsEn: ['Can\'t profit', 'Controls overtrading, high quality', 'Limits gains', 'Unnecessary'], explanationEn: 'Hard limit forces best-opportunity-only. Quality >> quantity.' },
  ],

  // ==========================================
  // ch6: 实战交易策略
  // ==========================================
  ch6: [
    { question: 'Retest策略相比追突破的优势是什么？', options: ['更刺激', '止损明确、入场逻辑清晰', '杠杆更高', '胜率100%'], correctIndex: 1, explanation: 'Retest等价格回来找你，止损放在明确位置（突破位），不需要预测方向。' , questionEn: 'Retest advantage over chasing breakouts?', optionsEn: ['Exciting', 'Clear stop loss, clear logic', 'Higher leverage', '100% win rate'], explanationEn: 'Price comes to you, clear stop at breakout level.' },
    { question: 'Retest的4步结构按顺序是什么？', options: ['确认→推动→回撤→延续', '推动→回撤→确认→延续', '回撤→推动→延续→确认', '延续→推动→回撤→确认'], correctIndex: 1, explanation: '初始推动(Impulse)→回撤(Pullback)→确认(Confirmation)→延续(Continuation)。' , questionEn: 'Retest 4-step order?', optionsEn: ['Confirm→Impulse→Pull→Continue', 'Impulse→Pullback→Confirm→Continue', 'Pull→Impulse→Continue→Confirm', 'Continue→Impulse→Pull→Confirm'], explanationEn: 'Impulse → Pullback → Confirmation → Continuation.' },
    { question: 'Retest策略中为什么止损设得比较宽（35%）？', options: ['鼓励冒险', '通过小仓位控制实际风险，避免假跌破打止损', '止损不重要', '只是建议'], correctIndex: 1, explanation: '宽止损+小仓位=给交易呼吸空间。Retest经常有假跌破，太紧的止损会被反复打掉。' , questionEn: 'Why is Retest stop wide (35%)?', optionsEn: ['Encourages risk', 'Small position controls risk; avoids false-breakdown stops', 'Doesn\'t matter', 'Suggestion'], explanationEn: 'Wide stop + small position = breathing room for false breakdowns.' },
    { question: '资金分类中，RC代表什么？', options: ['总储备', '分配给加密市场的储备', '月收入', '杠杆资金'], correctIndex: 1, explanation: 'RC = Reserve for Crypto，从总储备R中分配给加密市场的资金比例。' , questionEn: 'What does RC stand for?', optionsEn: ['Total reserve', 'Reserve for Crypto', 'Monthly income', 'Leveraged capital'], explanationEn: 'RC = Reserve for Crypto.' },
    { question: '底部分数=0.5时，应该投入RC的多少？', options: ['0%', '30%', '50%', '100%'], correctIndex: 2, explanation: '底部分数=0.5时投入RC和IC的50%。分数=投入比例，简单明了。' , questionEn: 'Bottom score = 0.5 → deploy what % of RC?', optionsEn: ['0%', '30%', '50%', '100%'], explanationEn: 'Score 0.5 → 50% of RC and IC.' },
    { question: '为什么顶部卖出不清仓（保留30%）？', options: ['忘了卖', '应对"这次不一样"的可能+BTC长期上涨趋势', '手续费太高', '没有原因'], correctIndex: 1, explanation: '保留30%是因为BTC长期向上，完全清仓意味着可能再也买不回来。' , questionEn: 'Why not sell 100% at top (keep 30%)?', optionsEn: ['Forgot', 'Hedge + BTC long-term uptrend', 'High fees', 'No reason'], explanationEn: '30% hedges BTC\'s upward trajectory.' },
    { question: 'Retest交易应该在什么时候入场？', options: ['突破瞬间', 'H6确认K线收盘后', '随时', '回撤最深处'], correctIndex: 1, explanation: '必须等H6确认K线收盘后才入场，不要在K线形成中途入场。收盘=确认完成。' , questionEn: 'When to enter Retest trade?', optionsEn: ['At breakout', 'After H6 confirmation close', 'Anytime', 'Deepest pullback'], explanationEn: 'Wait for H6 confirmation candle close.' },
    { question: '以下哪个是Retest策略的常见错误？', options: ['等确认', '追突破不等回撤', '止损太宽', '仓位太小'], correctIndex: 1, explanation: '追突破是最常见的错误。正确做法是等价格回测突破位，而不是追上去。' , questionEn: 'Common Retest mistake?', optionsEn: ['Waiting for confirmation', 'Chasing breakout without pullback', 'Wide stop', 'Small position'], explanationEn: 'Chasing without waiting for pullback is most common.' },
    { question: '"只在新高分数时增加仓位"这个规则的意义是？', options: ['增加风险', '避免在分数下降时减仓（单向建仓）', '减少手续费', '提高收益'], correctIndex: 1, explanation: '分数下降不减仓，只在分数创新高时加仓。这确保建仓是渐进式的，不会因为短期波动而反复操作。' , questionEn: '\'Only add at new high scores\' significance?', optionsEn: ['More risk', 'Prevents reducing on dips (one-way)', 'Fewer fees', 'More returns'], explanationEn: 'Don\'t reduce on dips; only add at new highs. Gradual building.' },
    { question: '"精准出手"比DCA好在哪里？', options: ['更简单', '更好的入场价+更低心理负担+更少手续费', '完全没有风险', 'DCA更好'], correctIndex: 1, explanation: '等信号集中建仓，入场价格更好、操作更少、心理压力更小。DCA在明显顶部也在买入=浪费弹药。' , questionEn: '\'Precision striking\' vs DCA advantage?', optionsEn: ['Simpler', 'Better entry + less stress + fewer fees', 'Risk-free', 'DCA better'], explanationEn: 'Signal-based entries = better prices, fewer ops, less stress.' },
    { question: 'Retest策略推荐的执行时间框架是什么？', options: ['1分钟', '1小时', 'H6（6小时）', '月线'], correctIndex: 2, explanation: 'H6能过滤掉小级别噪音，又有足够精度。Retest是中周期策略，不适合太小的时间框架。' , questionEn: 'Recommended Retest execution timeframe?', optionsEn: ['1-min', '1-hour', 'H6 (6-hour)', 'Monthly'], explanationEn: 'H6 filters noise with sufficient precision.' },
    { question: '分批建仓的核心逻辑是什么？', options: ['看起来专业', '无法精确判断最低点，分批获得更好平均成本', '手续费优惠', '习惯问题'], correctIndex: 1, explanation: '没有人能精确预测最低点。分批买入平滑入场成本，降低单次判断失误的风险。' , questionEn: 'Core logic of batch building?', optionsEn: ['Professional look', 'Can\'t pinpoint bottom; batching = better avg', 'Fee discounts', 'Habit'], explanationEn: 'Nobody predicts exact bottoms. Batch = smoother cost.' },
  ],

  // ==========================================
  // ch7: 真实案例分析
  // ==========================================
  ch7: [
    { question: 'LUNA崩盘中，大多数受害者的核心错误是什么？', options: ['技术不好', '单一资产过度集中+不理解底层机制', '时间框架不对', '杠杆太高'], correctIndex: 1, explanation: '大多数人把大部分积蓄放在单一项目，且不理解"算法稳定币"和"银行存款"的区别。' , questionEn: 'Core mistake of LUNA crash victims?', optionsEn: ['Poor skills', 'Over-concentrated + didn\'t understand mechanism', 'Wrong TF', 'Too much leverage'], explanationEn: 'Most put savings in one project without understanding algo stablecoins.' },
    { question: 'UST脱锚初期（$0.98）退出最多亏多少？', options: ['2%', '20%', '50%', '98%'], correctIndex: 0, explanation: '初期只亏2%。但"再等等"心态让2%变成98%+。止损的价值：小亏vs大亏。' , questionEn: 'Max loss exiting at UST $0.98?', optionsEn: ['2%', '20%', '50%', '98%'], explanationEn: 'Initially 2%. \'Just wait\' → 98%+.' },
    { question: '20% APY的Anchor协议，收益实际来自哪里？', options: ['银行存款', '真实商业利润', '不可持续的代币补贴机制', '国债收益'], correctIndex: 2, explanation: '如果你不知道收益从哪来，你就是收益来源。20%APY远超正常水平，背后没有真实可持续收入。' , questionEn: 'Where did Anchor 20% APY come from?', optionsEn: ['Bank deposits', 'Business profits', 'Unsustainable token subsidy', 'Treasury yields'], explanationEn: 'If you don\'t know where yield comes from, you ARE the yield.' },
    { question: '案例中$8K到$1.5M的交易者，最关键的错误是？', options: ['最初买入时机不对', '没有在盈利时锁定利润', '选错币种', '用错交易所'], correctIndex: 1, explanation: '利润不锁定=从未赚到。如果在$1.5M时提出50%，即使后面全亏也还有$750K。' , questionEn: '$8K→$1.5M trader\'s critical mistake?', optionsEn: ['Wrong timing', 'Failed to lock profits', 'Wrong coin', 'Wrong exchange'], explanationEn: 'Profits not locked = never earned. 50% at $1.5M = $750K safe.' },
    { question: '"牛市让每个人觉得自己是天才"的含义是？', options: ['牛市很简单', '在牛市中赚钱不需要技术，真正考验是熊市', '所有人都是天才', '牛市没有风险'], correctIndex: 1, explanation: '牛市中做多=赚钱，跟个人能力关系不大。真正的技术是在熊市中保住利润。' , questionEn: '\'Bull market genius\' meaning?', optionsEn: ['Easy', 'Profit needs no skill; test is bear market', 'All genius', 'No risk'], explanationEn: 'Long = profit regardless of skill. True skill: bear market survival.' },
    { question: '案例中的交易者在$38K用什么补保证金？', options: ['储蓄', '朋友借款', '信用卡', '工资'], correctIndex: 2, explanation: '用信用卡借钱补保证金是最危险的行为之一。亏了自己的钱还能重来，亏了借来的钱=人生困境。' , questionEn: 'What covered margin at $38K?', optionsEn: ['Savings', 'Friend\'s loan', 'Credit cards', 'Salary'], explanationEn: 'Credit cards for margin = extremely dangerous.' },
    { question: '关于LUNA案例，以下哪个说法正确？', options: ['只有散户亏钱', '连专业机构（Galaxy Digital）也亏了$5.58亿', '所有人都提前跑了', '只在韩国有影响'], correctIndex: 1, explanation: '不只是散户，连Novogratz的Galaxy Digital（专业机构）也在LUNA上亏损$5.58亿。叙事陷阱不分专业/业余。' , questionEn: 'About LUNA case, which is correct?', optionsEn: ['Only retail lost', 'Galaxy Digital lost $558M too', 'Everyone escaped', 'Only Korea'], explanationEn: 'Institutions lost too. Narrative traps don\'t discriminate.' },
    { question: '"心理账户效应"在案例中如何表现？', options: ['不知道账户密码', '把纸上利润当成自己的钱', '多开了几个账户', '转账手续费'], correctIndex: 1, explanation: '从$1.5M跌到$400K时感觉"亏了$1.1M"，但本金只有$8K。纸上利润不等于实际利润。' , questionEn: '\'Mental accounting\' manifestation?', optionsEn: ['Forgot password', 'Treated paper profits as real', 'Multiple accounts', 'Transfer fees'], explanationEn: '$1.5M→$400K felt like \'losing $1.1M\' but principal was $8K.' },
    { question: '单一资产投入应该不超过总资金的多少？', options: ['50%', '30%', '20%', '80%'], correctIndex: 2, explanation: '建议单一资产不超过总资金的20%。超过这个比例，一个项目的失败就可能造成难以恢复的损失。' , questionEn: 'Single asset max % of total?', optionsEn: ['50%', '30%', '20%', '80%'], explanationEn: 'Max 20%. Above = one failure causes irrecoverable damage.' },
    { question: '从这些案例中，最重要的资金保护规则是？', options: ['永远不亏钱', '设定不可逾越的底线+利润及时锁定', '只做多不做空', '杠杆越低越好'], correctIndex: 1, explanation: '两个核心：设定绝对底线（亏损到X%强制停止）+利润及时提取（翻倍后提出50%本金）。' , questionEn: 'Most important capital protection rule?', optionsEn: ['Never lose', 'Set limits + lock profits', 'Only long', 'Lower leverage'], explanationEn: 'Absolute stop limit + timely profit withdrawal.' },
    { question: '案例交易者从"谨慎"到"狂妄"用了多久？', options: ['1个月', '6个月', '约1年', '3年'], correctIndex: 2, explanation: '从2020年3月到2021年4月，约1年。从谨慎兴奋到"我是天才"，市场的连续正反馈会快速改变心态。' , questionEn: 'Cautious to arrogant — how long?', optionsEn: ['1 month', '6 months', '~1 year', '3 years'], explanationEn: 'March 2020 to April 2021, ~1 year.' },
    { question: '以下哪个不是从案例中学到的教训？', options: ['永远不要用借来的钱交易', '区分运气和技术', '牛市应该更激进', '利润要及时锁定'], correctIndex: 2, explanation: '牛市恰恰应该更警惕——容易过度自信。正确做法是在牛市中逐步锁定利润，而不是更激进。' , questionEn: 'Which is NOT a lesson from cases?', optionsEn: ['Never trade borrowed money', 'Distinguish luck from skill', 'Be more aggressive in bull markets', 'Lock profits'], explanationEn: 'Bull markets should increase vigilance, not aggression.' },
  ],
};
